databases:
  source:
    name: this_live
  target:
    name: this_train

tables:
  primary_table:
    name: "your_actual_table_name"  # Replace with your table name
    primary_key: "id"  # The primary key column of your main table
  dependencies:
    foreign_key_column: "primary_id"  # The column name other tables use to reference the primary table
    primary_key: "id"  # The primary key column used in dependent tables

export:
  sample_percentage: 20
  random_seed: 42
  batch_size: 1000

essential_records:
  records:
    - id: 1001
    - id: 1002
  include_dependencies: true

excluded_tables:
  - training_config
  - train_specific_data

scrubbing:
  random_names:
    - table: customers
      fields: [first_name, last_name]
      style: github
    - table: employees
      fields: [name]
      style: github
    - table: projects
      fields: [project_name]
      style: github
    - table: repositories
      fields: [repo_name]
      style: github
  
  standardize:
    address:
      value: "123 Training St, Test City, ST 12345"
      fields:
        - table: customers
          field: address
        - table: employees
          field: address
    
    phone:
      value: "555-0123"
      fields:
        - table: customers
          field: phone
        - table: employees
          field: phone
    
    email:
      value: "test@example.com"
      fields:
        - table: customers
          field: email
        - table: employees
          field: email

  combination_fields:
    - table: projects
      fields:
        - source_field: name1
          random_style: github
        - source_field: name2
          random_style: github
      separator: "-&-"
      target_field: combo_name
    - table: repositories
      fields:
        - source_field: owner_name
          random_style: github
        - source_field: repo_name
          random_style: github
      separator: "/"
      target_field: full_path