databases:
  source:
    name: this_live
    dsn: live_dsn
  target:
    name: this_train
    dsn: train_dsn

# Export settings
export:
  # Percentage of non-essential records to export (0-100)
  sample_percentage: 20
  # Random seed for consistent sampling
  random_seed: 42
  # Batch size for processing
  batch_size: 1000

# Essential records to always include
essential_records:
  main_table:
    - id: 1001
    - id: 1002
    include_dependencies: true

# Tables to exclude from export
excluded_tables:
  - training_config
  - train_specific_data

# Fields to scrub
scrubbing:
  randomize_names:
    - table: customers
      fields: [first_name, last_name]
    - table: employees
      fields: [name]
  
  standardize:
    address:
      value: "123 Training St, Test City, ST 12345"
      fields:
        - table: customers
          field: address
        - table: employees
          field: address
    
    phone:
      value: "555-0123"
      fields:
        - table: customers
          field: phone
        - table: employees
          field: phone
    
    email:
      value: "test@example.com"
      fields:
        - table: customers
          field: email
        - table: employees
          field: email

  github_style_names:
    - table: projects
      field: project_name
    - table: repositories
      field: repo_name