databases:
  source:
    name: this_live
  target:
    name: this_train
  testing:
    test_db: test_live        # Database to use as mock production
    temp_verify: temp_verify  # Temporary verification database
    verification_marker: "VERIFY_TEST_STRING_XYZ_"  # Marker for excluded tables

export:
  sample_percentage: 20
  random_seed: 42
  batch_size: 1000

essential_records:
  main_table:
    - id: 1001
    - id: 1002
    include_dependencies: true

excluded_tables:
  - training_config
  - train_specific_data

verification:
  logging:
    directory: logs
    prefix: verify_
  checksums:
    enabled: true
    algorithm: md5sum  # or sha256sum
  record_counts:
    enabled: true
    sample_tables:     # Tables to check record counts (empty = all)
      - customers
      - employees
  excluded_table_samples: 3  # Number of top/bottom records to mark

scrubbing:
  # Consolidated name randomization
  random_names:
    - table: customers
      fields: [first_name, last_name]
      style: github
    - table: employees
      fields: [name]
      style: github
    - table: projects
      fields: [project_name]
      style: github
    - table: repositories
      fields: [repo_name]
      style: github
  
  standardize:
    address:
      value: "123 Training St, Test City, ST 12345"
      fields:
        - table: customers
          field: address
        - table: employees
          field: address
    
    phone:
      value: "555-0123"
      fields:
        - table: customers
          field: phone
        - table: employees
          field: phone
    
    email:
      value: "test@example.com"
      fields:
        - table: customers
          field: email
        - table: employees
          field: email

  combination_fields:
    - table: projects
      fields:
        - source_field: name1
          random_style: github
        - source_field: name2
          random_style: github
      separator: "-&-"
      target_field: combo_name
    - table: repositories
      fields:
        - source_field: owner_name
          random_style: github
        - source_field: repo_name
          random_style: github
      separator: "/"
      target_field: full_path